# Generated by Django 4.0.3 on 2022-03-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='text',
            field=models.TextField(default='', verbose_name='Text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
