# Generated by Django 4.0.3 on 2022-03-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_slider_created_at_slider_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='button_link',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='button_text',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
