# Generated by Django 4.0.3 on 2022-03-03 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service_subservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_services', to='core.service'),
        ),
    ]
