# Generated by Django 4.0.3 on 2022-03-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_subservice_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='sub_image',
            field=models.ImageField(default='', upload_to='icons/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
