version: '3'
services:
  postgres:
    container_name: postgres-db
    image: postgres:9.6
    ports:
      - 5432:5432 # Bind host port 5432 to PostgreSQL port 5432
    volumes:
      - ./postgredb:/var/lib/postgresql/data
    env_file: .env
    environment:
      - LC_ALL=C.UTF-8
      - VIRTUAL_HOST=postgres
      - VIRTUAL_PORT=5432
  web:
    build: .
    restart: "always"
    ports:
      - "80:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
      - ./media/:/code/media/
    links:
      - postgres
    depends_on:
      - 'postgres'